# Generated by Django 5.1.1 on 2025-02-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_ban_community_alter_ban_expires_at_alter_ban_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ban',
            old_name='member',
            new_name='user',
        ),
    ]
