# Generated by Django 5.1.1 on 2025-02-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_rename_member_ban_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
