# Generated by Django 5.1.1 on 2025-02-14 20:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_ban_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'community')},
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'community')},
        ),
    ]
