# Generated by Django 5.1.1 on 2025-01-29 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_block_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='follower',
        ),
        migrations.RemoveField(
            model_name='block',
            name='user',
        ),
        migrations.AddField(
            model_name='block',
            name='blocked_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
