# Generated by Django 5.1.1 on 2025-01-31 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_block_blocked_by_alter_block_blocked_user_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocked_by', 'blocked_user')},
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'followed')},
        ),
    ]
